import {engineChapterMarkup} from './src/engine/chapter.js';
import {monitorMarkup} from './src/monitor-scene.js';
import {writeFileSync} from 'node:fs';
import {CHAPTERS,FIELDS} from './src/content.js';
import {renderLearningMarkup} from './src/learning/index.js';
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const nav=CHAPTERS.map((c,i)=>`<a href="#${c.id}" aria-label="${i+1}. ${c.name}"><span>0${i+1}</span><b>${c.name}</b></a>`).join('');
const sections=CHAPTERS.map((c,i)=>`<section class="chapter" id="${c.id}" aria-labelledby="title-${c.id}"><div class="chapter-inner"><div class="copy"><p class="eyebrow">${c.place}</p><${i?'h2':'h1'} id="title-${c.id}">${c.title.replaceAll('\n','<br>')}</${i?'h2':'h1'}><p class="lead">${c.lead}</p><button class="primary js-only" data-open="${i}">${c.action}<span aria-hidden="true">↗</span></button><details class="lesson"><summary>O que isso muda no meu trabalho?</summary><p>${c.body}</p><p>${c.lesson}</p><a href="${c.source}" target="_blank" rel="noopener">${c.sourceName} ↗</a><button class="lesson-close js-only" type="button">Fechar</button></details>${i===2?'<button id="inspect-engine" type="button" class="secondary js-only">Dentro do motor ↗</button>':''}${i===0?'<p class="scroll-hint">ROLE PARA COMEÇAR <span aria-hidden="true">↓</span></p>':''}${i===5?'<a class="restart" href="#preparar">↶ Voltar ao início com o registro preservado</a>':''}</div></div></section>`).join('');
const inputs=FIELDS.map(([key,label,hint])=>`<label class="field" for="field-${key}"><span>${label}</span><textarea id="field-${key}" name="${key}" rows="2" placeholder="${esc(hint)}" maxlength="10000"></textarea></label>`).join('');
writeFileSync(new URL('./index.html',import.meta.url),`<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#101619"><meta name="description" content="Uma aula de engenharia de loop com IA, no laboratório de um carro de fórmula. Defina critérios, confronte evidências e registre a próxima decisão."><title>Engenharia de Loop · INTEIA</title><script>document.documentElement.classList.add('js')</script><link rel="icon" href="data:,"><link rel="stylesheet" href="./src/style.css"><link rel="stylesheet" href="./src/learning/learning.css"></head>
<body><a class="skip" href="#preparar">Ir para a aula</a>
<div id="stage" aria-hidden="true"><img class="poster" src="./assets/box-poster.webp" alt=""></div><div class="shade" aria-hidden="true"></div>
<div id="preloader"><div class="pre-inner"><img src="./assets/INTEIA-negativo.svg" alt="" aria-hidden="true"><p class="pre-kicker" aria-hidden="true">ENGENHARIA DE LOOP</p><div class="pre-meter" aria-hidden="true"><i></i></div><p class="pre-status" aria-hidden="true"><span id="preload-text">Preparando o box</span><span><b id="preload-pct">00</b>%</span></p><button id="preload-read" type="button">Ler a aula sem 3D</button></div></div>
<button id="hotspot" class="off" type="button" tabindex="-1" aria-hidden="true"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="h-arc" cx="60" cy="60" r="57"/><circle class="h-disc" cx="60" cy="60" r="43"/><circle class="h-ring" cx="60" cy="60" r="43"/></svg><i class="h-lead" aria-hidden="true"></i><span id="hotspot-label"></span></button>
<header><a class="brand" href="#preparar" aria-label="INTEIA — início"><img src="./assets/INTEIA-negativo.svg" alt="INTEIA"><span>ENGENHARIA DE LOOP</span></a><div class="header-actions"><button id="reading" class="js-only" aria-pressed="false">Modo leitura</button><button id="notebook" class="js-only">Meu registro <span aria-hidden="true">↗</span></button></div></header>
<nav class="chapters-nav" aria-label="Etapas da aula">${nav}<a href="#motor-do-loop" aria-label="7. Motor do loop"><span>07</span><b>Motor</b></a></nav><main>${sections.replace(/(?=<section[^>]*id="corrigir")/,monitorMarkup())}${engineChapterMarkup()}</main>
<footer><span class="footer-title">INTEIA <i>/</i> ENGENHARIA DE LOOP</span><span id="scene-label">BOX</span><span id="load-state" role="status"></span><div class="progress" aria-hidden="true"><i id="progress-bar"></i></div></footer>
<dialog id="lesson-dialog" aria-labelledby="dialog-title"><div class="dialog-top"><span class="eyebrow">ATIVIDADE</span><button class="close" data-close aria-label="Fechar atividade">×</button></div><p id="dialog-step" class="eyebrow"></p><h2 id="dialog-title"></h2><h3 class="dialog-phase">1 · Pratique no caso</h3>${renderLearningMarkup()}<fieldset id="quiz"><legend id="question"></legend><div id="choices"></div><p id="feedback" role="status"></p></fieldset><h3 class="dialog-phase">2 · Agora na sua tarefa real</h3><p id="dialog-example" class="dialog-example" hidden></p><div id="extra-fields"></div><label class="field" for="quick-note"><span id="quick-label"></span><textarea id="quick-note" rows="3" maxlength="10000"></textarea></label><p class="small">Use sua tarefa real. A anotação fica neste navegador.</p><button id="save-note" class="primary">Concluir e fechar <span>↗</span></button><div class="f1-note"><span>NA FÓRMULA 1</span><p id="dialog-f1"></p><a id="dialog-source" target="_blank" rel="noopener"></a></div></dialog>
<dialog id="notebook-dialog" aria-labelledby="notebook-title"><div class="dialog-top"><span class="eyebrow">MEU REGISTRO</span><button class="close" data-close aria-label="Fechar registro">×</button></div><h2 id="notebook-title">TAREFA, EVIDÊNCIA<br>E DECISÃO</h2><p>Registre uma tarefa real do seu trabalho, etapa por etapa.</p><form id="notebook-form">${inputs}<label class="field" for="decision"><span>Minha decisão com base na evidência</span><select id="decision" name="decision"><option value="">Ainda não decidi</option><option value="aceitar">Aceitar: critério conferido por mim</option><option value="reverter">Reverter: regressão identificada</option><option value="revisar">Revisar: falha delimitada</option><option value="inconclusivo">Parar: inconclusivo / limite atingido</option><option value="decisao-necessaria">Decisão necessária: consequência fora do escopo</option></select></label></form><p id="storage-state" role="status">As anotações ficam somente neste navegador.</p><div class="button-row"><button id="export" class="primary">Baixar registro <span>↓</span></button><button id="prompt" class="secondary">Gerar prompt de revisão</button></div><label class="field" for="prompt-output" id="prompt-wrap" hidden><span>Prompt para levar à sua IA</span><textarea id="prompt-output" rows="9" readonly></textarea></label><div class="button-row" id="copy-row" hidden><button id="copy-prompt" class="secondary" type="button">Copiar prompt</button><span id="copy-state" class="small" role="status"></span></div><p class="small">Baixe uma cópia do registro para retomar a tarefa depois.</p></dialog>
<noscript><section class="lr-static-reading"><p>Prática para leitura: confira a fonte e registre suas respostas em papel. A conferência interativa exige JavaScript.</p>${renderLearningMarkup().replace(/<noscript>[\s\S]*?<\/noscript>/g,'')}</section><div class="noscript">Aula em modo leitura. Ative JavaScript para explorar o carro e usar o caderno interativo.</div></noscript><script type="module" src="./src/main.js"></script></body></html>`);
