import {writeFileSync} from 'node:fs';
import {CHAPTERS,FIELDS} from './src/content.js';
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const nav=CHAPTERS.map((c,i)=>`<a href="#${c.id}" aria-label="${i+1}. ${c.name}"><span>0${i+1}</span><b>${c.name}</b></a>`).join('');
const sections=CHAPTERS.map((c,i)=>`<section class="chapter" id="${c.id}" aria-labelledby="title-${c.id}"><div class="chapter-inner"><div class="copy"><p class="eyebrow">${c.place}</p><${i?'h2':'h1'} id="title-${c.id}">${c.title.replaceAll('\n','<br>')}</${i?'h2':'h1'}><p class="lead">${c.lead}</p><p class="principle">${c.principle}</p><button class="primary js-only" data-open="${i}">${c.action}<span aria-hidden="true">↗</span></button><details class="lesson"><summary>O que isso muda no meu trabalho?</summary><p>${c.body}</p><p>${c.lesson}</p><a href="${c.source}" target="_blank" rel="noopener">${c.sourceName} ↗</a></details>${i===0?'<p class="scroll-hint">ROLE PARA COMEÇAR <span aria-hidden="true">↓</span></p>':''}${i===5?'<a class="restart" href="#preparar">↶ Voltar ao início com o registro preservado</a>':''}</div></div></section>`).join('');
const inputs=FIELDS.map(([key,label,hint])=>`<label class="field" for="field-${key}"><span>${label}</span><textarea id="field-${key}" name="${key}" rows="2" placeholder="${esc(hint)}" maxlength="10000"></textarea></label>`).join('');
writeFileSync(new URL('./index.html',import.meta.url),`<!doctype html>
<html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#101619"><meta name="description" content="Uma aula de engenharia de loop com IA, no laboratório de um carro de fórmula. Defina critérios, confronte evidências e registre a próxima decisão."><title>BOX, BOX. — Engenharia de Loop · INTEIA</title><link rel="icon" href="data:,"><link rel="stylesheet" href="./src/style.css"></head>
<body><a class="skip" href="#preparar">Ir para a aula</a>
<div id="stage" aria-hidden="true"><img class="poster" src="./assets/box-poster.png" alt=""></div><div class="shade" aria-hidden="true"></div><div id="wipe" aria-hidden="true"></div>
<header><a class="brand" href="#preparar" aria-label="INTEIA — início"><img src="./assets/INTEIA-negativo.svg" alt="INTEIA"><span>ENGENHARIA DE LOOP</span></a><div class="header-actions"><button id="reading" class="js-only" aria-pressed="false">Modo leitura</button><button id="notebook" class="js-only">Meu registro <span aria-hidden="true">↗</span></button></div></header>
<aside class="signature" aria-hidden="true">BOX, BOX.<span>SEIS ETAPAS DE UM LOOP</span></aside><nav class="chapters-nav" aria-label="Etapas da aula">${nav}</nav><main>${sections}</main>
<footer><span class="footer-title">INTEIA <i>/</i> APRENDER A ITERAR</span><span id="scene-label">BOX · REFERÊNCIA</span><span id="load-state" role="status">A aula está pronta para leitura</span><div class="progress" aria-hidden="true"><i id="progress-bar"></i></div></footer>
<dialog id="lesson-dialog" aria-labelledby="dialog-title"><div class="dialog-top"><span class="eyebrow">BOX DE APRENDIZAGEM</span><button class="close" data-close aria-label="Fechar atividade">×</button></div><p id="dialog-step" class="eyebrow"></p><h2 id="dialog-title"></h2><p id="dialog-body"></p><div class="f1-note"><span>O QUE A F1 ENSINA</span><p id="dialog-f1"></p><a id="dialog-source" target="_blank" rel="noopener"></a></div><fieldset id="quiz"><legend id="question"></legend><p class="small">Situação didática para você avaliar.</p><div id="choices"></div><p id="feedback" role="status"></p></fieldset><label class="field" for="quick-note"><span id="quick-label"></span><textarea id="quick-note" rows="3" maxlength="10000"></textarea></label><p class="small">Use sua tarefa real. A anotação fica neste navegador.</p><button id="save-note" class="primary">Guardar no meu registro <span>↗</span></button></dialog>
<dialog id="notebook-dialog" aria-labelledby="notebook-title"><div class="dialog-top"><span class="eyebrow">REGISTRO DO SEU LOOP</span><button class="close" data-close aria-label="Fechar registro">×</button></div><h2 id="notebook-title">A PRÓXIMA VOLTA<br>COMEÇA AQUI.</h2><p>Registre uma tarefa real. Os campos começam vazios; preencher este caderno não certifica o resultado.</p><form id="notebook-form">${inputs}<label class="field" for="decision"><span>Minha decisão com base na evidência</span><select id="decision" name="decision"><option value="">Ainda não decidi</option><option value="aceitar">Aceitar: critério conferido por mim</option><option value="reverter">Reverter: regressão identificada</option><option value="revisar">Revisar: falha delimitada</option><option value="inconclusivo">Parar: inconclusivo / limite atingido</option><option value="decisao-necessaria">Decisão necessária: consequência fora do escopo</option></select></label></form><p id="storage-state" role="status">Anotações salvas somente neste navegador.</p><div class="button-row"><button id="export" class="primary">Baixar registro <span>↓</span></button><button id="prompt" class="secondary">Gerar prompt de revisão</button></div><label class="field" for="prompt-output" id="prompt-wrap" hidden><span>Prompt para levar à sua IA</span><textarea id="prompt-output" rows="9" readonly></textarea></label><p class="small">As respostas dos exercícios e a rolagem não aprovam sua tarefa automaticamente. Leve uma cópia do registro para o próximo ciclo.</p></dialog>
<noscript><div class="noscript">Aula em modo leitura. Ative JavaScript para explorar o carro e usar o caderno interativo.</div></noscript><script type="module" src="./src/main.js"></script></body></html>`);
