// Fonte de conteúdo da aula. Fontes F1 conferidas no complemento de pesquisa
// e, para Ferrari/Monza e o debrief McLaren, nas páginas públicas em 13/09/2026.
// Os casos históricos sustentam a lição; o carro animado é uma ilustração.
export const CHAPTERS = [
  {id:'preparar',name:'Preparar',place:'01 / BOX INTEIA',title:'ANTES DE MUDAR,\nDEFINA O PRONTO.',lead:'Uma volta começa com um critério. Sem ele, você só está dando voltas.',principle:'Referência → critério → limite',body:'Escolha uma tarefa real. Guarde a versão inicial, escreva o resultado esperado e diga o que não pode piorar. Antes de pedir à IA que melhore, defina como você vai conferir.',action:'Definir meu critério',field:'criterion',extra:['task','reference'],prompt:'Qual resultado observável fará você aceitar esta tarefa? Registre também o que deve permanecer correto.',lesson:'Na F1, a preparação no simulador ajuda a estabelecer uma configuração inicial. Na sua tarefa, uma versão de referência permite comparar a mudança.',source:'https://www.mercedesamgf1.com/news/feature-explaining-the-role-of-an-f1-sim-driver',sourceName:'Mercedes · O trabalho no simulador',question:'Você pede à IA para melhorar um resumo. Qual critério permite conferir o resultado?',choices:['Ficar mais profissional.','Preservar todas as datas e sustentar cada afirmação na fonte.','Receber uma nota alta de outra IA.'],correct:1,feedback:'Um critério precisa ser observável. A aparência e uma nota isolada não demonstram fidelidade à fonte.'},
  {id:'hipotese',name:'Hipótese',place:'02 / BANCADA DE ENGENHARIA',title:'UMA IDEIA.\nUM TESTE.',lead:'Explique o que a mudança deve causar — e o que provaria que você está errado.',principle:'Mudança delimitada → previsão',body:'Escolha uma alteração por vez quando quiser entender sua causa. Escreva a previsão antes de ver a resposta. Assim você evita inventar uma justificativa depois que o resultado chega.',action:'Escrever minha hipótese',field:'hypothesis',prompt:'Se eu mudar ___, espero observar ___, porque ___. Vou rejeitar essa hipótese se ___.',lesson:'Simulador e pista precisam ser comparados. A previsão é uma hipótese de trabalho; a evidência da pista pode contrariá-la.',source:'https://www.formula1.com/en/latest/article/testing-explained-rob-smedley-on-correlation-aero-rakes-and-flow-vis-paint.5UTaH1q9iuQcXVjZXui3Fz',sourceName:'Formula 1 · Correlação, aero rakes e flow-vis',question:'Você mudou o prompt, o modelo e a fonte ao mesmo tempo. O resultado melhorou. O que você pode concluir?',choices:['O novo prompt causou a melhora.','O modelo novo é sempre melhor.','O resultado mudou; ainda não foi isolada a causa.'],correct:2,feedback:'Mudar várias condições pode ser útil para explorar. Para atribuir a melhora a uma delas, é preciso uma comparação que isole essa mudança.'},
  {id:'executar',name:'Executar',place:'03 / TÚNEL DE ENSAIO',title:'MUDE POUCO.\nGUARDE A VERSÃO.',lead:'Produza uma candidata que possa ser comparada, criticada e desfeita.',principle:'Produzir → preservar → observar',body:'Dê à IA a fonte, o escopo e o critério. Guarde a candidata e a referência separadamente. Rodar um teste produz uma observação; ainda falta interpretar o que ela permite afirmar.',action:'Preparar meu teste',field:'test',prompt:'Que ação vou executar, em qual versão e com qual entrada? Como vou guardar a saída para outra pessoa conferir?',lesson:'Aero rakes e flow-vis ajudam a investigar o comportamento do ar. Neste site, os traços são uma ilustração visual: não medem o escoamento deste carro.',source:'https://www.formula1.com/en/latest/article/testing-explained-rob-smedley-on-correlation-aero-rakes-and-flow-vis-paint.5UTaH1q9iuQcXVjZXui3Fz',sourceName:'Formula 1 · Como os testes investigam o carro',question:'A IA escreveu “verificado”. O que fecha a verificação?',choices:['Ler a fonte ou executar o teste e conferir sua saída.','Pedir para escrever “verificado” duas vezes.','A resposta estar bem apresentada.'],correct:0,feedback:'Uma declaração de verificação não é a evidência. Guarde a fonte consultada, a versão avaliada e o resultado observado.'},
  {id:'avaliar',name:'Avaliar',place:'04 / ESTAÇÃO DE ENGENHARIA',title:'PARECE BOM.\nMAS PASSOU?',lead:'O crítico precisa de provas, de um critério e de espaço para discordar.',principle:'Criticar → conferir → decidir',body:'Dê ao revisor a candidata, os critérios e as fontes necessárias. Peça falhas concretas e confira os achados. Outro agente pode ajudar, mas também pode repetir erros. Uma revisão pode não encontrar falhas: nesse caso, deve dizer o que verificou e quais são seus limites.',action:'Registrar minha evidência',field:'evidence',prompt:'O que foi observado, em qual versão e onde isso pode ser conferido? O critério passou, falhou ou continua sem evidência suficiente?',lesson:'A Mercedes destaca a seleção de dados relevantes para a análise. No seu loop, escolha a evidência que responde ao critério; quantidade de dados sozinha não decide se o trabalho atende.',source:'https://www.mercedesamgf1.com/news/feature-data-and-electronics-in-f1-explained',sourceName:'Mercedes · Dados e eletrônica na F1',question:'Dois agentes aprovaram o texto, mas nenhum abriu a fonte. Qual é o estado?',choices:['Aprovado por consenso.','Inconclusivo: falta conferir a evidência.','Reprovado automaticamente.'],correct:1,feedback:'Concordância pode orientar a revisão, mas não substitui evidência. Sem a conferência exigida, a conclusão continua inconclusiva.'},
  {id:'corrigir',name:'Corrigir',place:'05 / VOLTA AO BOX',title:'CORRIJA O ERRO.\nCONFIRA DE NOVO.',lead:'Melhorar uma parte não compensa estragar outra que já funcionava.',principle:'Revisar → verificar regressões',body:'Corrija a falha demonstrada e confira de novo o que mudou e o que precisava permanecer correto. Se houve regressão, compare com a referência e preserve o trabalho ao restaurá-la. Só mude um critério com fundamento registrado. Se a candidata já atende, não invente uma correção.',action:'Planejar minha correção',field:'correction',prompt:'Qual falha foi demonstrada? Qual a menor correção útil? O que vou conferir novamente? Se não há correção necessária, qual evidência permite aceitar?',lesson:'O piso da Ferrari para Monza 2024 buscava controlar as oscilações surgidas com a atualização de Barcelona. A vitória em Monza não prova que essa mudança causou o resultado. Aqui, a peça animada ilustra uma revisão; não demonstra ganho aerodinâmico.',source:'https://www.formula1.com/en/latest/article/tech-weekly-how-ferraris-monza-upgrades-helped-the-team-to-address-a-key.5UpzTp0C4wEAuH8HalwblV',sourceName:'Formula 1 · Ferrari em Monza: trecho público da análise técnica',question:'A nova versão ficou mais clara, mas removeu uma informação obrigatória. O que fazer?',choices:['Aceitar porque ficou bonita.','Apagar o critério que falhou.','Corrigir ou reverter; testar fidelidade e clareza novamente.'],correct:2,feedback:'Uma regressão precisa entrar na decisão. Não torne o teste mais permissivo apenas para aceitar a candidata.'},
  {id:'encerrar',name:'Encerrar',place:'06 / DEBRIEF',title:'DECIDA. REGISTRE.\nRECOMECE MELHOR.',lead:'O fim da volta é uma decisão sustentada. O registro é a largada da próxima.',principle:'Decisão → evidência → próximo passo',body:'Aceite quando os critérios estiverem conferidos. Se faltar prova ou o orçamento acabar, registre “inconclusivo”. Se surgir uma consequência fora do escopo combinado, registre a decisão necessária. Guarde o resultado, os limites e a próxima pergunta antes de continuar.',action:'Concluir meu registro',field:'next',extra:['decision'],prompt:'Que decisão a evidência permite? O que ainda falta ou precisa ser decidido? Qual entrada você deixará para a próxima volta?',lesson:'A McLaren descreve o debrief como uma conversa estruturada entre engenharia e pilotos que orienta os ajustes da sessão seguinte. No seu loop, o registro conecta o resultado à próxima decisão. O carro montado não comprova que a tarefa foi concluída.',source:'https://www.mclaren.com/racing/formula-1/2026/what-do-formula-1-drivers-do-between-sessions/',sourceName:'McLaren · Debrief e preparação da próxima sessão',question:'O limite de tempo terminou e faltou um teste obrigatório. Como encerrar?',choices:['Marcar sucesso para concluir a entrega.','Registrar inconclusivo, a lacuna e o próximo passo.','Repetir indefinidamente sem mudar o plano.'],correct:1,feedback:'Parar por limite é uma decisão válida. Ela não equivale a sucesso: a evidência faltante deve acompanhar o registro.'}
];

export const FIELDS = [
 ['task','Minha tarefa real','Descreva uma tarefa pequena que você já precisa realizar.'],
 ['reference','Fonte e versão de referência','Indique o documento, arquivo ou endereço e a versão inicial.'],
 ['criterion','Critério e o que não pode piorar','Escreva um resultado observável e o que precisa ser preservado.'],
 ['hypothesis','Hipótese','Se eu mudar…, espero…, e rejeitarei se…'],
 ['test','Teste e limite','Registre ação, entrada e limite de tempo, custo ou tentativas.'],
 ['evidence','Evidência observada','Registre a saída real e onde pode ser conferida.'],
 ['correction','Correção e regressões','O que mudou e o que foi conferido novamente?'],
 ['next','Pendência e próxima volta','O que outra pessoa precisa saber para continuar?']
];
